apiVersion: v1
kind: Service
metadata:
  name: node-exporter-svc
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP