apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom
  template:
    metadata:
      labels:
        app: prom
    spec:
      containers:
      - name: prom
        image: prom/prometheus
        ports:
        - containerPort: 9090