apiVersion: v1
kind: Service
metadata:
  name: prom-svc-lb
  labels:
    app: prom
spec:
  selector:
    app: prom
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP